### PR TITLE
Change timing of saves and detection of ctrl-c

### LINKED ISSUE #248: Ctrl-c at timetable initialisation cause application to spam the user before quitting
image

### LINKED ISSUE #254: Ctrl-c at command prompt causes exception
image

### PR DESCRIPTION
**Pull request by Aseanseen**
### NoSuchElementException is thrown when user enters ctrl-c so I made the following adjustments

* NoSuchElementException is thrown out to the main class to be caught. Note that it does not do anything after catching.
* InputOutputManager.save() has been moved to the Executor
* InputOutputManager.saveNusMods() has been moved to the main class under start()

Please note the difference in output for the 2 possible methods to terminate the program.
1. `bye`

image

2. CTRL-C

image

Fixes #248, fixes #254

### CODE REVIEW

File: src/main/java/seedu/ravi/Ravi.java [hunk 1]
```diff
@@ -24,9 +26,9 @@
      */
     public static void main(String[] args) {
         Runtime.getRuntime().addShutdownHook(new Thread(() -> {
-            logger.getLogger().info("Shutdown hook - Saving all data...");
-            InputOutputManager.save();
-            InputOutputManager.saveNusMods();
+            logger.getLogger().info("Shutdown hook");
+            System.out.println();
+            TextUi.outputToUser(MESSAGE_GOODBYE);
```
Comment (Aseanseen) [inline src/main/java/seedu/ravi/Ravi.java]: I realise now that if one were to enter `bye` into the prompt, it will cause `MESSAGE_GOODBYE` to be printed twice, once in the execution of the `ExitCommand` and once here. This is because Java cannot differentiate between a normal `System.exit` and CTRL-C.

Any suggestions on what to do? I was thinking of removing this shutdownhook and printing the bye in the NoSuchElement exception caught. Or removing the exitcommand and use this as an exit.

Comment (SimJunYou) [reply src/main/java/seedu/ravi/Ravi.java]: We can just remove the printing of `MESSAGE_GOODBYE` in `ExitCommand` because whenever the shutdown occurs it will print the message anyways

File: src/main/java/seedu/ravi/Executor.java [hunk 2]
```diff
@@ -19,6 +20,7 @@ public static CommandResult executeCommand(String userInput) {
 
         if (command.getPromptType() == PromptType.EDIT) {
             StateManager.saveState(userInput);
+            InputOutputManager.save();
```
Comment (SimJunYou) [inline src/main/java/seedu/ravi/Executor.java:23]: Why is the saving moved to the executor?

**Review by SimJunYou — CHANGES_REQUESTED** [review]
Some comments

File: src/main/java/seedu/ravi/Executor.java (hunk 2 above)
Comment (Aseanseen) [reply src/main/java/seedu/ravi/Executor.java:23]: I moved it here because it was stated in this guide that the shutdown hook should be fast. So I decided to move it to `PromptType.Edit` commands.

https://www.geeksforgeeks.org/jvm-shutdown-hook-java/

image
image

File: src/main/java/seedu/ravi/Ravi.java (hunk 1 above)
Comment (Aseanseen) [reply src/main/java/seedu/ravi/Ravi.java]: Changed the message to be printed in shutdown hook

**Review by SimJunYou — APPROVED** [review]
Let's go
