### PR TITLE
Fixed Cap and Grade Bugs, minor edits to UG

### LINKED ISSUE #163: [PE-D] task name creation
task name does not read characters after hyphens

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: randynyl/ped#1

### LINKED ISSUE #195: [PE-D] Issue on "grade" command on Team CS2113T-T09-2
Steps to reproduce
1. Add cs1231s by `add -m cs1231s`
2. Delete cs1231s by `delete -m cs1231s`
3. Add back cs1231s by `add -m cs1231s`
4. Grade cs1231s as A+ by `grade -m cs1231s A+`

Major error caught! The program throw an uncaugt error and terminated itself.

Sugested Solution: Review the implementation of `grade` command

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: felixhalim/ped#11

### LINKED ISSUE #213: [PE-D] The welcome statement “In here,…” is a bit vague
The vague welcome message can cause confusion to user.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: tienkhoa16/ped#4

### PR DESCRIPTION
**Pull request by tobiasceg**
Fixes #213 , #216 , #217 , #218 , #223 , #224 , #182 , #203 , #204, #205 , #180 , #181 , #163 
previous PR fixed #195

### CODE REVIEW

File: src/main/java/seedu/duke/exception/InvalidCapAttained.java [hunk 1]
```diff
@@ -0,0 +1,4 @@
+package seedu.duke.exception;
+
+public class InvalidCapAttained extends Exception {
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/exception/InvalidCapAttained.java]: Maybe rename to InvalidCapCalculatedException?

File: src/main/java/seedu/duke/util/Message.java [hunk 2]
```diff
@@ -60,7 +60,8 @@
             + "\t▻ bye       → Exit ra.VI (saves all changes!)";
     public static final String MESSAGE_TIMETABLE_INIT =
             "Please enter the current week num e.g. 1 - 14"
-                    + " where 7 is recess week.\n" + "In here, NUS week 7 onwards is week 8 onwards.";
+                    + " where 7 is recess week.\n" + "In RaVi, NUS week 7 onwards is week 8 onwards. \n"
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/util/Message.java]: Application name should be ra.VI

File: src/main/java/seedu/duke/util/Message.java [hunk 3]
```diff
@@ -60,7 +60,8 @@
...
+                    + "For example, in Academic week 9, please input the current weak num to be 10";
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/util/Message.java]: Typo of "week"

File: src/main/java/seedu/duke/util/ExceptionMessage.java [hunk 4]
```diff
@@ -67,7 +69,12 @@
     public static final String MESSAGE_DATE_TIME_UNKNOWN =
             "Please enter a valid date and time.\n"
             + "You can use help <command> to find the required date time format.\n";
-
+    public static final String MESSAGE_INVALID_CAP =
+            "Amazing you have entered an invalid cap, Good try. \n";
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/util/ExceptionMessage.java]: Capital letter after comma not recommended

File: src/main/java/seedu/duke/util/ExceptionMessage.java [hunk 5]
```diff
@@ -67,7 +69,12 @@
...
+    public static final String MESSAGE_INVALID_CAP_ATTAINED =
+            "Amazing you have attained an Invalid cap, on purpose or not? \n";
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/util/ExceptionMessage.java]: Singlish not recommended

File: src/main/java/seedu/duke/util/ExceptionMessage.java [hunk 6]
```diff
@@ -67,7 +69,12 @@
...
+    public static final String MESSAGE_INVALID_MC =
+            "Amazing you have entered an invalid number of module credits taken, Nice try. \n";
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/util/ExceptionMessage.java]: Capital letter after comma not recommended

File: src/test/java/seedu/duke/command/grade/GradeCommandTest.java [hunk 7]
```diff
@@ -30,23 +34,25 @@ void setupModObjects() {
...
         GradeCommand gradeCommand = new GradeCommand(NON_EXISTENT_MODULE_CODE, 4, "A+");
         CommandResult commandResult = gradeCommand.execute();
-        assertEquals(ExceptionMessage.MESSAGE_MODULE_NOT_FOUND, commandResult.feedbackToUser);
+        assertEquals(centerString(MAX_WIDTH, EXCEPTION_HEADER) + "\n" + ExceptionMessage.MESSAGE_MODULE_NOT_FOUND,
+                commandResult.feedbackToUser);
     }
 
     @Test
-    void gradeCommand_MessageInvalidGrade_isShown() {
+    void gradeCommand_MessageInvalidGrade_isShown() throws InvalidModuleCreditException {
```
Comment (Aseanseen) [inline src/test/java/seedu/duke/command/grade/GradeCommandTest.java:52]: Line 53, singlish not recommended

**Review by Aseanseen — CHANGES_REQUESTED** [review]
Some amends suggested

File: src/main/java/seedu/duke/command/cap/CapCommand.java [hunk 8]
```diff
@@ -62,23 +88,47 @@ private double gradeConvert(String grade) {
...
+    /**
+     * Calculates the cap of the user.
+     *
+     * @return
+     * cap of the user
+     * @throws InvalidCapAttained
+     * When the attained cap is unimaginable
+     */
+    private double calculateCap() throws InvalidCapAttained {
         HashMap<String, Module> moduleList = ModuleManager.getModulesMap();
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/command/cap/CapCommand.java]: As mentioned before, please use `ModuleManager.getModCodeList()` instead of directly accessing the `modulesMap` object.

File: src/main/java/seedu/duke/command/cap/CapCommand.java [hunk 9]
```diff
@@ -62,23 +88,47 @@ private double gradeConvert(String grade) {
...
         double mcGrade;
         double sumMcGrade = 0;
         double sumMc = 0;
+        double gradeValue = 0;
         for (String i : moduleList.keySet()) {
+            gradeValue = gradeConvert(moduleList.get(i).getModuleGrade());
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/command/cap/CapCommand.java]: Same here for line 105 and 106 regarding `ModuleManager`.

File: src/main/java/seedu/duke/command/cap/CapCommand.java [hunk 10]
```diff
@@ -62,23 +88,47 @@ private double gradeConvert(String grade) {
...
+            if (gradeValue == 0) {
+                throw new InvalidCapAttained();
+            }
             sumMc += moduleList.get(i).getModuleCredit();
             mcGrade = moduleList.get(i).getModuleCredit()
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/command/cap/CapCommand.java]: Same here for line 110 and 111 regarding `ModuleManager`.

File: src/main/java/seedu/duke/command/cap/CapCommand.java [hunk 11]
```diff
@@ -62,23 +88,47 @@ private double gradeConvert(String grade) {
...
-        return Cap;
+        cap = ((currentCap * totalMcTaken) + sumMcGrade) / (sumMc + totalMcTaken);
+        if (cap < 0 || cap > 5.0 || isNan(cap)) {
+            throw new InvalidCapAttained();
+        }
+        return cap;
+    }
+
+    private boolean isNan(double cap) {
+        return cap != cap;
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/command/cap/CapCommand.java:123]: Uh... `this.cap != cap`?

Comment (SimJunYou) [reply src/main/java/seedu/duke/command/cap/CapCommand.java:123]: Okay that doesn't make sense too... can you explain this part?

File: src/main/java/seedu/duke/command/grade/GradeCommand.java [hunk 12]
```diff
@@ -83,9 +85,9 @@ public CommandResult execute() {
             grade();
             return new CommandResult(MESSAGE_GRADE_MODULE_SUCCESS);
         } catch (InvalidGradeException e) {
-            return new CommandResult(MESSAGE_INVALID_GRADE);
+            return new CommandResult(centerString(MAX_WIDTH, EXCEPTION_HEADER) + "\n" + MESSAGE_INVALID_GRADE);
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/command/grade/GradeCommand.java:91]: Nice that you're using `centerString`, but generally all `CommandResult` messages don't use `centerString` I think, except for the error messages. Possible to remove to standardise?

File: src/main/java/seedu/duke/command/cap/CapCommand.java [hunk 13]
```diff
@@ -62,23 +88,47 @@ private double gradeConvert(String grade) {
...
+    private double calculateCap() throws InvalidCapAttained {
         HashMap<String, Module> moduleList = ModuleManager.getModulesMap();
         double mcGrade;
         double sumMcGrade = 0;
         double sumMc = 0;
+        double gradeValue = 0;
         for (String i : moduleList.keySet()) {
+            gradeValue = gradeConvert(moduleList.get(i).getModuleGrade());
+            if (gradeValue == 0) {
+                throw new InvalidCapAttained();
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/command/cap/CapCommand.java]: Can I check how you're handling SUs? SUs should be worth 0 "grade points" no?

File: src/main/java/seedu/duke/exception/InvalidCapAttained.java (hunk 1 above)
Comment (SimJunYou) [reply src/main/java/seedu/duke/exception/InvalidCapAttained.java]: Seconded

File: src/main/java/seedu/duke/util/ExceptionMessage.java [hunk 14]
```diff
@@ -39,13 +39,15 @@
...
+            + "Or the number you have entered is too long... \n"
             + "Please check your command! Use help <command> for assistance.\n";
     public static final String MESSAGE_INVALID_COMMAND_WORD =
             "I don't recognise that command...\n"
             + "Please use help to see our list of commands.\n";
     public static final String MESSAGE_INVALID_GRADE =
             "Your grade input isn't part of the NUS grading scheme. \n"
-            + "For your reference: A+, A, A-, B+, B, B-, C+, C, C-, D+, F.\n";
+            + "For your reference: A+, A, A-, B+, B, B-, C+, C, C-, D+, F. \n"
+            + "Grades CS,CU,S,U are not accepted. \n";
```
Comment (SimJunYou) [inline src/main/java/seedu/duke/util/ExceptionMessage.java]: Insert space after comma.

**Review by SimJunYou — CHANGES_REQUESTED** [review]
Some changes to be made

File: src/main/java/seedu/duke/exception/InvalidCapAttained.java (hunk 1 above)
Comment (tobiasceg) [reply src/main/java/seedu/duke/exception/InvalidCapAttained.java]: thirded, motion granted

File: src/main/java/seedu/duke/util/Message.java (hunk 3 above)
Comment (tobiasceg) [reply src/main/java/seedu/duke/util/Message.java]: that typo was meant for you, thank you

File: src/main/java/seedu/duke/command/grade/GradeCommand.java (hunk 12 above)
Comment (tobiasceg) [reply src/main/java/seedu/duke/command/grade/GradeCommand.java:91]: but the locations where i have used centerstrings are actually the error messages as the catches are in execute and they return commandresult instead of incorrectcommand thus for such specific cases i have included the error headers

**Review by Aseanseen — APPROVED** [review]
Looks good to merge, but please fix the conflicts before merging

**Review by SimJunYou — APPROVED** [review]
LGTM
