### PR TITLE
Granular loading and fixed task status loading

### LINKED ISSUE #126: Bug regarding the saving of ravi
Marking a task as done and exiting the application then running the application again will cause the task to no longer be marked as done.\
Steps to reproduce:
* add -t test
* done 1
* list -t
* bye
* list -t

### PR DESCRIPTION
**Pull request by SimJunYou**
As shown in picture. Also, fixes #126 .
image

### CODE REVIEW

**Review by tobiasceg — APPROVED** [review]
wp jy wp

File: src/main/java/seedu/duke/data/storage/InputOutputManager.java [hunk 1]
```diff
@@ -46,59 +52,85 @@
...
-                }
-            } catch (JSONException e) {
-                logger.getLogger().severe("JSON string can't be parsed! Is it corrupted?");
-                renameCorruptedFiles();
-                status = 2; // 'Corrupted' status
-            }
+            // For documentation of this part, look at TextUi's showWelcomeMessage
+            status += tryLoadMods();
+            status += tryLoadTasks() * 10;
+            status += tryLoadTimetable() * 100;
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/data/storage/InputOutputManager.java:65]: Maybe try to use enums instead to improve readability?

File: src/main/java/seedu/duke/ui/TextUi.java [hunk 2]
```diff
@@ -49,33 +50,47 @@ public TextUi(Scanner in) {
...
+            switch (latestCode) {
+            case 0:
+                statusMsg = "Skipped (file not found!)";
+                break;
+            case 1:
+                statusMsg = "Success!";
+                break;
+            case 2:
+                statusMsg = "Failed (corrupted file auto-renamed)";
+                break;
```
Comment (Aseanseen) [inline src/main/java/seedu/duke/ui/TextUi.java:81]: Same comment as above, I do see the explanation in the javadoc but it might be better to change to enums

**Review by Aseanseen — APPROVED** [review]
Some suggestions, but otherwise ok to merge

File: src/main/java/seedu/duke/ui/TextUi.java (hunk 2 above)
Comment (SimJunYou) [reply src/main/java/seedu/duke/ui/TextUi.java:81]: There will be a total of 27 enums which will have names like `MOD_SUCCESS_TASK_FAILURE_TIMETABLE_SKIP` which I think is less readable than this. I think this is an acceptable loss in readability since it's only being passed between 2 functions.

Comment (SimJunYou) [reply src/main/java/seedu/duke/ui/TextUi.java:81]: Also I'll need 27 conditional branches in order to return the right enum 😨
